# This is a basic workflow to help you get started with Actions

name: CppUTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Preparing Build System
        run: |  # define a custom multi-line command (instead of a reusable action) for this step
          sudo apt-get update
          #sudo apt-get install build-essential gcc g++ bison flex perl python3 libxml2-dev zlib1g-dev default-jre doxygen graphviz
          sudo apt-get install cpputest lcov
        
      ## Runs all unit tests
      #- name: Run unit tests
      #  run: |
      #    cd test
      #    make

      # Runs all units tests with coverage report
      - name: Run unit tests with coverage report
        run: |
          cd test
          make lcov
      - name: Where are we?
        run: pwd
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: test/build/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
